name: Deploy new data

on:
  schedule:
    - cron: "47,*/60 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        KYOTO_ADDR: ${{ secrets.KYOTO_ADDR }}
        MY_ADDR:  ${{ secrets.MY_ADDR }}
      run: |
        python main.py ${CLIENT_ID} ${CLIENT_SECRET} ${REFRESH_TOKEN} ${KYOTO_ADDR} ${MY_ADDR}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        publish_branch: gh-pages
        allow_empty_commit: true
